name: kidszone_app
description: Mutlu çocuklar mutlu yarınlar

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+0003

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  animations: ^2.0.7
  async: ^2.10.0
  auto_route: ^5.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  buttons_tabbar: ^1.3.6
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3

  dio: ^4.0.6
  easy_localization: 3.0.2-dev
  flex_color_picker: ^2.6.1
  flutter:
    sdk: flutter
  flutter_easy_permission: ^1.1.2
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^1.1.3
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.6+4
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_svg: ^1.1.6
  get_it: ^7.2.0

  http: ^0.13.5
  image_cropper: ^3.0.0
  image_picker: ^0.8.6
  injectable: ^1.5.3
  json_annotation: ^4.7.0

  #extensions kütüphaneleri
  kartal: ^2.3.2
  intl: ^0.17.0-nullsafety.2
  
  localstorage: ^4.0.0+1
 
  mobx: ^2.1.1
  mobx_codegen: ^2.0.7+3
  nb_utils: ^4.6.22
  network_to_file_image: ^4.0.1
  package_info: ^2.0.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  provider: ^6.0.4

  #ekran tipini algılama
  universal_platform: ^1.0.0+1
  responsive_builder: ^0.4.3
  #bottom bar
  google_nav_bar: ^5.0.6

  sqflite: ^2.1.0+1
  top_snackbar_flutter: ^2.1.1
  vexana: ^3.0.1
  # video_player: ^2.4.7
  # video_player_platform_interface: ^5.1.4
    
  #video player
  double_tap_player_view: ^2.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.3
  video_player: ^2.4.8
  chewie: ^1.3.5

  #socket io client 
  socket_io_client: ^2.0.0
  flutter_chat_ui: ^1.6.6
  file_picker: ^5.2.2
  open_filex: ^4.2.2
  uuid: ^3.0.6
  responsive_table: ^0.2.0+2
  
  #video_thumbnail: ^0.5.2
  #video_trimmer: ^1.1.3

dev_dependencies:
  build_runner: ^2.3.2
  easy_localization_generator: ^0.0.3
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.2
  flutter_gen_runner: ^5.0.3
  #very_good_analysis: ^3.1.0
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true

  assets:
    - resources/langs/
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Quicksand
      fonts:
      - asset: assets/fonts/Quicksand-Bold.ttf
      - asset: assets/fonts/Quicksand-Light.ttf
      - asset: assets/fonts/Quicksand-Medium.ttf
      - asset: assets/fonts/Quicksand-Regular.ttf
      - asset: assets/fonts/Quicksand-SemiBold.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-BlackItalic.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-BoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraBold.ttf
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/Nunito-ExtraLight.ttf
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
        - asset: assets/fonts/Nunito-Light.ttf
        - asset: assets/fonts/Nunito-LightItalic.ttf
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf

  # fonts:
    # - family: Andina
    #   fonts:
    #     - asset: fonts/andina.ttf

    # - family: Regular
    #   fonts:
    #     - asset: fonts/googlesansregular.ttf

    # - family: Medium
    #   fonts:
    #     - asset: fonts/googlesansmedium.ttf

    # - family: Semibold
    #   fonts:
    #     - asset: fonts/googlesansmedium.ttf

    # - family: Bold
    #   fonts:
    #     - asset: fonts/googlesansebold.ttf

targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
