name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 1.5.2
homepage: https://github.com/Milad-Akarie/injectable
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.2.1
  source_gen: ^1.2.1
  path: ^1.8.0
  glob: ^2.0.2
  analyzer: ^3.2.0
  code_builder: ^4.1.0
  dart_style: ^2.2.0
  injectable:
    path: ../injectable/
  
  collection: ^1.15.0
dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  test: ^1.20.1
